//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class BookView
    {
        public string ISBN { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public long authorId { get; set; }
        public long genreId { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public string Author { get; set; }
        public string Genre { get; set; }
        public Nullable<int> NumOfLikes { get; set; }
    }
}
